name: "Mihoyo StarRail SignIn"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install packages 
        run: npm install
      - name: run sign
        run: node dist/main.js
        env:
          S_COOKIE_STRING: ${{secrets.S_COOKIE_STRING}}
          L_COOKIE_STRING: ${{secrets.L_COOKIE_STRING}}
          WECHAT_COOKIE_STRING: ${{secrets.WECHAT_COOKIE_STRING}}
          SR_UID: ${{secrets.SR_UID}}
          QY_WECHAT: ${{secrets.QY_WECHAT}}
      - uses: actions/upload-artifact@v2
        with:
          name: mihoyo-log
          path: log/mihoyo.log
